debug: true
server:
  port:
spring:
  sql:
    init:
      platform: postgresql
      mode: always
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name:
    url: jdbc:postgresql://ajajanas-server.postgres.database.azure.com:5432/guest
    username: nantia@ajajanas-server
    password: Episalt1337

  jpa:
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR