debug: true
server:
  port:
spring:
  sql:
    init:
      platform: postgresql
      mode: always
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name:
    url: jdbc:postgresql://mouse.db.elephantsql.com/hvppjzoq
    username: hvppjzoq
    password: hALFNfe87sfhckxRewcmTsoUrFomAD4x
  jpa:
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR